plugins:
  - jekyll-relative-links
  - jekyll-remote-theme
relative_links:
  enabled: true
  collections: true
include:
  - README.md
remote_theme: pages-themes/slate@v0.2.0
title: OpenJDK for Legacy macOS Versions
description: Ports of the newest versions of Java to unsupported versions of OS X/macOS
markdown: GFM